# Generated by Django 4.1.7 on 2023-06-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbank',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileCode', to='profile_app.profile'),
        ),
    ]
