# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion
import mostanadat_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standardTable_app', '0001_initial'),
        ('profile_app', '0001_initial'),
        ('process_app', '0001_initial'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('boolean', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'دیتابیس  bool',
                'verbose_name_plural': 'دیتابیس  bool',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('confirm', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر')], max_length=75)),
                ('text', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmationProfileMostanadatDakheli', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'دیتابیس  کانفرم شدن',
                'verbose_name_plural': 'دیتابیس  کانفرم شدن',
            },
        ),
        migrations.CreateModel(
            name='MostanadatDakheli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dakheliSanadCode', models.CharField(max_length=100)),
                ('versionNumber', models.CharField(max_length=100)),
                ('tabaghbandi', models.CharField(choices=[('محرمانه', 'محرمانه '), ('غیرمحرمانه', 'غیرمحرمانه')], max_length=100)),
                ('molahezat', models.TextField(blank=True, max_length=500, null=True)),
                ('outdated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('systemMortabetCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systemCode', to='standardTable_app.standard')),
            ],
            options={
                'verbose_name': 'مستندات درون سازمانی ',
                'verbose_name_plural': 'مستندات درون سازمانی ',
            },
        ),
        migrations.CreateModel(
            name='MostanadatDakheliChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(blank=True, choices=[('create', 'تدوین سند'), ('edit', 'اصلاح سند'), ('delete', 'حذف صند')], max_length=75, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documentRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MostanadatDakheli', to='mostanadat_app.mostanadatdakheli')),
                ('vahedRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MostanadatDakheliChangeVahed', to='organization_app.vahed')),
            ],
            options={
                'verbose_name': 'درخواست تغییر',
                'verbose_name_plural': 'درخواست تغییر',
            },
        ),
        migrations.CreateModel(
            name='TextDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'دیتابیس متن ها',
                'verbose_name_plural': 'دیتابیس متن ها',
            },
        ),
        migrations.CreateModel(
            name='TypeMadrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('typeMadrakCode', models.CharField(blank=True, max_length=100, null=True)),
                ('ekhtesat', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع مدرک ',
                'verbose_name_plural': 'نوع مدرک ',
            },
        ),
        migrations.CreateModel(
            name='RecordDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('recordCode', models.CharField(max_length=100)),
                ('privacy', models.CharField(choices=[('internal', 'داخلی'), ('secret', 'محرمانه')], max_length=75)),
                ('typeKeeping', models.CharField(choices=[('electronic', 'الکترونیکی'), ('paper', 'کاغذی')], max_length=75)),
                ('determine', models.TextField(blank=True, null=True)),
                ('jariY', models.IntegerField(blank=True, null=True)),
                ('jariM', models.IntegerField(blank=True, null=True)),
                ('rakedY', models.IntegerField(blank=True, null=True)),
                ('rakedM', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postKeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postKeeper', to='organization_app.typepostsazmani')),
                ('vahedKeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vahedKeeper', to='organization_app.vahed')),
            ],
            options={
                'verbose_name': 'لیست سوابق   ',
                'verbose_name_plural': ' لیست سوابق ',
            },
        ),
        migrations.CreateModel(
            name='RecordChangeActivityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('done', 'done'), ('doing', 'doing'), ('completed', 'completed'), ('delete', 'delete')], default='doing', max_length=75)),
                ('activity', models.CharField(choices=[('register', 'ثبت درخواست '), ('barresiMafogh', 'تاییدیه اولیه مافوق'), ('barresiKarshenas', 'بررسی کارشناس دفتر توسعه مدیریت و تحقیقات'), ('barresiModir', 'بررسی مدیر دفتر توسعه مدیریت و تحقیقات'), ('editKarshenas', 'اصلاح اطلاعات لیست کنترل سوابق')], max_length=75)),
                ('file', models.FileField(blank=True, null=True, upload_to=mostanadat_app.models.user_directory_path_mostanadatDakheli_change)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('RecordChangeRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecordChangeRelated', to='mostanadat_app.recorddatabase')),
                ('bools', models.ManyToManyField(related_name='RecordBoolData', to='mostanadat_app.booldatabase')),
                ('confirmations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmationRecordData', to='mostanadat_app.confirmationdatabase')),
                ('nextActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NeActivityMostanadatDakheliChange', to='mostanadat_app.recordchangeactivitymanager')),
                ('previousActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrActivityMostanadatDakheliChange', to='mostanadat_app.recordchangeactivitymanager')),
                ('reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReciverProfileRecordChange', to='profile_app.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SenderProfileRecordChange', to='profile_app.profile')),
                ('texts', models.ManyToManyField(related_name='RecordTextData', to='mostanadat_app.textdatabase')),
            ],
            options={
                'verbose_name': 'مدیریت فعالیت های درخواست اصلاح سوابق',
                'verbose_name_plural': 'مدیریت فعالیت های درخواست اصلاح سوابق',
            },
        ),
        migrations.CreateModel(
            name='RecordChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recordRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MostanadatDakheli', to='mostanadat_app.recorddatabase')),
            ],
            options={
                'verbose_name': 'درخواست تغییر سابقه',
                'verbose_name_plural': 'درخواست تغییر سابقه',
            },
        ),
        migrations.CreateModel(
            name='MostanadatKhareji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kharejiSanadCode', models.CharField(blank=True, max_length=100, null=True)),
                ('versionNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('entesharDate', models.CharField(blank=True, max_length=100, null=True)),
                ('etebarDate', models.CharField(blank=True, max_length=100, null=True)),
                ('refrenceName', models.CharField(blank=True, max_length=250, null=True)),
                ('expiredDate', models.CharField(blank=True, max_length=250, null=True)),
                ('updatePeriod', models.CharField(blank=True, max_length=100, null=True)),
                ('tozihat', models.TextField(blank=True, max_length=500, null=True)),
                ('govermentUpdate', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postmasolUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postMasol', to='organization_app.typepostsazmani')),
                ('processCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesCode', to='process_app.process')),
            ],
            options={
                'verbose_name': 'مستندات برون سازمانی ',
                'verbose_name_plural': 'مستندات برون سازمانی',
            },
        ),
        migrations.CreateModel(
            name='MostanadatDakheliChangeActivityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('done', 'done'), ('doing', 'doing'), ('completed', 'completed')], default='doing', max_length=75)),
                ('activity', models.CharField(choices=[('register', 'اطلاعات اولیه'), ('barresiMafogh', 'تاییدیه اولیه مافوق'), ('barresiKarshenas', 'بررسی کارشناس دفتر توسعه مدیریت و تحقیقات'), ('barresiModir', 'بررسی مدیر دفتر توسعه مدیریت و تحقیقات'), ('tadvinSanad', 'تدوین مدرک جدید'), ('isDelete', 'آیا سند حذف می شود ؟'), ('newDoc', 'بارگزاری و تدوین سند جدید'), ('editDoc', 'ویرایش سند جدید'), ('reform', 'اصلاح و تکمیل مدارک')], max_length=75)),
                ('file', models.FileField(blank=True, null=True, upload_to=mostanadat_app.models.user_directory_path_mostanadatDakheli_change)),
                ('startTiem', models.DateTimeField(blank=True, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MostanadatDakheliChangeRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MostanadatDakheliRelated', to='mostanadat_app.mostanadatdakhelichange')),
                ('bools', models.ManyToManyField(related_name='BoolData', to='mostanadat_app.booldatabase')),
                ('confirmations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmationData', to='mostanadat_app.confirmationdatabase')),
                ('nextActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NeActivityMostanadatDakheliChange', to='mostanadat_app.mostanadatdakhelichangeactivitymanager')),
                ('previousActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrActivityMostanadatDakheliChange', to='mostanadat_app.mostanadatdakhelichangeactivitymanager')),
                ('reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReciverProfileMostanadatDakheliChange', to='profile_app.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SenderProfileMostanadatDakheliChange', to='profile_app.profile')),
                ('texts', models.ManyToManyField(related_name='textData', to='mostanadat_app.textdatabase')),
            ],
            options={
                'verbose_name': 'مدیریت فعالیت های تغییر مستندات داخلی   ',
                'verbose_name_plural': 'مدیریت فعالیت های تغییر مستندات داخلی   ',
            },
        ),
        migrations.AddField(
            model_name='mostanadatdakheli',
            name='typeMadrakCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refrerence', to='mostanadat_app.typemadrak'),
        ),
        migrations.AddField(
            model_name='mostanadatdakheli',
            name='vahedMortabetCode',
            field=models.ManyToManyField(related_name='vahedMortabet', to='organization_app.vahed'),
        ),
        migrations.AddField(
            model_name='mostanadatdakheli',
            name='vahedMotevaliCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vahedMotevali', to='organization_app.vahed'),
        ),
        migrations.AddField(
            model_name='mostanadatdakheli',
            name='vahedTaeidCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postSazmaniTaeid', to='organization_app.typepostsazmani'),
        ),
        migrations.AddField(
            model_name='mostanadatdakheli',
            name='vahedTasvibCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postSazmaniTasvib', to='organization_app.typepostsazmani'),
        ),
    ]
