# Generated by Django 4.1.7 on 2023-10-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mostanadat_app', '0002_alter_mostanadatdakhelichange_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typemadrak',
            old_name='ekhtesat',
            new_name='ekhtesar',
        ),
    ]
