# Generated by Django 4.1.7 on 2023-07-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0002_alter_jobbank_profile'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibleAction', to='organization_app.jobbank'),
        ),
    ]
