# Generated by Django 4.1.7 on 2023-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_action_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
