# Generated by Django 4.1.7 on 2023-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_rename_starttime_action_starttiem'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
