# Generated by Django 4.1.7 on 2023-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_alter_action_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
