# Generated by Django 4.1.7 on 2023-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_action_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
