# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StandardReferenceRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persianReferenceName', models.CharField(blank=True, max_length=250, null=True)),
                ('englishReferenceName', models.CharField(blank=True, max_length=250, null=True)),
                ('namad', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.CharField(blank=True, max_length=60, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('standardTitlePersian', models.CharField(blank=True, max_length=250, null=True)),
                ('standardTitleEnglish', models.CharField(blank=True, max_length=250, null=True)),
                ('namad', models.CharField(blank=True, max_length=250, null=True)),
                ('vaziyatEjra', models.CharField(blank=True, choices=[('پیاده\u200cسازی شده و در حال اجرا', 'پیاده\u200cسازی شده و در حال اجرا'), ('در حال طرح\u200cریزی', 'در حال طرح\u200cریزی'), ('معلق', 'معلق'), ('جایگزین شده است', 'جایگزین شده است'), ('اقدامی صورت نگرفته', 'اقدامی صورت نگرفته')], max_length=250, null=True)),
                ('shamsiReleaseDate', models.CharField(blank=True, max_length=250, null=True)),
                ('miladiReleaseDate', models.CharField(blank=True, max_length=250, null=True)),
                ('tajdidNazarNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('language', models.CharField(blank=True, choices=[('فارسی', 'فارسی'), ('انگلیسی', 'انگلیسی')], max_length=250, null=True)),
                ('typeStandard', models.CharField(blank=True, choices=[('مدیریتی', 'مدیریتی'), ('فنی و تخصصی (عملیاتی)', 'فنی و تخصصی (عملیاتی)'), ('محصول', 'محصول'), ('سایر', 'سایر')], max_length=250, null=True)),
                ('geoDomainStandard', models.CharField(blank=True, choices=[('بین\u200cالمللی', 'بین\u200cالمللی'), ('منطقه\u200cای', 'منطقه\u200cای'), ('ملی', 'ملی'), ('سازمانی', 'سازمانی')], max_length=250, null=True)),
                ('internationalStandardReference', models.CharField(blank=True, max_length=250, null=True)),
                ('internationalStandardReferenceNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refrerence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refrerence', to='standardTable_app.standardreferencerelease')),
                ('vahedMortabetCode', models.ManyToManyField(blank=True, related_name='unitMortabetCode3', to='organization_app.vahed')),
                ('vahedMotevaliCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitMotevaliCode2', to='organization_app.vahed')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clauseNumber', models.CharField(blank=True, max_length=250, null=True, verbose_name='شماره بند')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('childClause', models.ManyToManyField(to='standardTable_app.requirementstandards', verbose_name='زیربند ها')),
                ('parentClause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='standardTable_app.requirementstandards', verbose_name='بند پدر')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standardTable_app.standard', verbose_name='Standard')),
            ],
            options={
                'verbose_name': 'الزامات استاندارد',
                'verbose_name_plural': 'الزامات استاندارد',
            },
        ),
    ]
