# Generated by Django 4.1.7 on 2023-06-13 17:27

import corrective_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standardTable_app', '0001_initial'),
        ('profile_app', '0001_initial'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('boolean', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'دیتابیس  bool',
                'verbose_name_plural': 'دیتابیس  bool',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('confirm', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر')], max_length=75)),
                ('text', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmationProfile', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'دیتابیس  کانفرم شدن',
                'verbose_name_plural': 'دیتابیس  کانفرم شدن',
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(blank=True, choices=[('correctiveAction', 'اقدام اصلاحی'), ('Correction', 'درخواست اصلاح')], max_length=75, null=True)),
                ('demandantId', models.CharField(max_length=250)),
                ('source', models.CharField(blank=True, choices=[('MomayeziDakheli', 'ممیزی داخلی '), ('risk', 'مدیریت ریسک '), ('پایش و اندازه گیری فرآیند', 'پایش و اندازه گیری فرآیند'), ('پایش و شناسایی تخلفات', 'پایش و شناسایی تخلفات'), ('ممیزی خارجی', 'ممیزی خارجی'), ('بازنگری و مدیریت', 'بازنگری و مدیریت'), ('مدیریت تغییر', 'مدیریت تغییر')], max_length=75, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('effective', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demandantVahed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandantVahed', to='organization_app.vahed')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerCorrectiveAction', to='profile_app.profile')),
                ('standardRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standardRelatedCorrective', to='standardTable_app.standard')),
                ('vahed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CorrectiveActionVahed', to='organization_app.vahed')),
            ],
            options={
                'verbose_name': 'اقدام اصلاحی',
                'verbose_name_plural': 'اقدام اصلاحی',
            },
        ),
        migrations.CreateModel(
            name='TextDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'دیتابیس متن ها',
                'verbose_name_plural': 'دیتابیس متن ها',
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionActivityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'done'), ('doing', 'doing'), ('completed', 'completed')], default='doing', max_length=75)),
                ('activity', models.CharField(choices=[('description', 'شرح مسئله/ درخواست'), ('barresiMafogh', 'بررسی درخواست توسط مافوق'), ('executiveUnit', 'تعیین واحد مجری '), ('register', 'ثبت اطلاعات پایه'), ('barresiModir', 'بررسی درخواست توسط مدیر'), ('cause', 'علت و ریشه '), ('barresiMoaven', 'بررسی درخواست توسط معاون'), ('definitionCorrectiveaAtion', 'تعریف اقدام اصلاحی'), ('ejraNatije', 'ثبت نتیجه اقدام'), ('confirmRiportMotevali', 'تایید گزارش  توسط واحد متولی'), ('confirmRiportModir', 'تایید گزارش  توسط مدیر دفتر توسعه مدیریت و تحقیقات'), ('effective', 'اثربخشی')], max_length=75)),
                ('file', models.FileField(blank=True, null=True, upload_to=corrective_app.models.user_directory_path_correctiveAction)),
                ('startTiem', models.DateTimeField(blank=True, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CorrectiveActionRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CorrectiveActionRelated', to='corrective_app.correctiveaction')),
                ('bools', models.ManyToManyField(related_name='BoolData', to='corrective_app.booldatabase')),
                ('confirmations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmationData', to='corrective_app.confirmationdatabase')),
                ('nextActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NeActivityCorrectiveAction', to='corrective_app.correctiveactionactivitymanager')),
                ('previousActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrActivityCorrectiveAction', to='corrective_app.correctiveactionactivitymanager')),
                ('reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReciverProfileCorrective', to='profile_app.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SenderProfileCorrective', to='profile_app.profile')),
                ('texts', models.ManyToManyField(related_name='textData', to='corrective_app.textdatabase')),
            ],
            options={
                'verbose_name': 'مدیریت فعالیت های اقدام اصلاحی   ',
                'verbose_name_plural': 'مدیریت فعالیت های اقدام اصلاحی   ',
            },
        ),
    ]
