# Generated by Django 4.1.7 on 2023-07-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveactionactivitymanager',
            name='bools',
            field=models.ManyToManyField(blank=True, null=True, related_name='BoolData', to='corrective_app.booldatabase'),
        ),
        migrations.AlterField(
            model_name='correctiveactionactivitymanager',
            name='texts',
            field=models.ManyToManyField(blank=True, null=True, related_name='textData', to='corrective_app.textdatabase'),
        ),
    ]
