# Generated by Django 4.1.7 on 2023-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_app', '0002_alter_correctiveactionactivitymanager_bools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveactionactivitymanager',
            name='bools',
            field=models.ManyToManyField(related_name='BoolData', to='corrective_app.booldatabase'),
        ),
        migrations.AlterField(
            model_name='correctiveactionactivitymanager',
            name='texts',
            field=models.ManyToManyField(related_name='textData', to='corrective_app.textdatabase'),
        ),
    ]
