# Generated by Django 4.1.7 on 2023-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceIndex_app', '0002_performancesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancesettings',
            name='endPeriod',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='performancesettings',
            name='startPeriod',
            field=models.IntegerField(default=1),
        ),
    ]
