# Generated by Django 4.1.7 on 2023-07-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceIndex_app', '0003_alter_performancesettings_endperiod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceindexactivitymanager',
            name='bools',
        ),
        migrations.RemoveField(
            model_name='performanceindexactivitymanager',
            name='sender',
        ),
        migrations.AddField(
            model_name='performanceindexactivitymanager',
            name='variableRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variableRelatedPerformanceIndexActivityManager', to='performanceIndex_app.variabledatabase'),
        ),
        migrations.AlterField(
            model_name='performanceindexactivitymanager',
            name='activity',
            field=models.CharField(choices=[('insert', 'ورود اطلاعات')], max_length=75),
        ),
        migrations.RemoveField(
            model_name='performanceindexactivitymanager',
            name='texts',
        ),
        migrations.AddField(
            model_name='performanceindexactivitymanager',
            name='texts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
