# Generated by Django 4.1.7 on 2023-08-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceIndex_app', '0004_remove_performanceindexactivitymanager_bools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceindexactivitymanager',
            name='activity',
            field=models.CharField(choices=[('insert', 'ورود اطلاعات')], default='insert', max_length=75),
        ),
    ]
