# Generated by Django 4.1.7 on 2023-07-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_event_alluser_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, choices=[('#F44335 ', 'red'), ('#4CAF50', 'green'), ('#fb8c00', 'orange')], default='سبز', max_length=8, null=True),
        ),
    ]
