# Generated by Django 4.1.7 on 2023-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, choices=[('#F44335 ', 'red'), ('#4CAF50', 'green'), ('#fb8c00', 'orange'), ('#1c3c60', 'blue')], default='سبز', max_length=8, null=True),
        ),
    ]
