# Generated by Django 4.1.7 on 2023-07-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momayezi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemomayezi',
            name='typeMomayeziCode',
        ),
    ]
