# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion
import report_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=report_app.models.user_directory_path_reoprt)),
                ('referabl', models.BooleanField(default=True)),
                ('forward', models.BooleanField(default=True)),
                ('arcane', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': ' گزارش',
                'verbose_name_plural': ' گزارش',
            },
        ),
        migrations.CreateModel(
            name='ReportActivityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'done'), ('doing', 'doing'), ('completed', 'completed')], default='doing', max_length=75)),
                ('text', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=report_app.models.user_directory_path_reoprt)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ReportRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportRelated', to='report_app.report')),
                ('nextActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NeActivityReport', to='report_app.reportactivitymanager')),
                ('previousActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrActivityReport', to='report_app.reportactivitymanager')),
                ('reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReciverReport', to='profile_app.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SenderReport', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'مدیریت فعالیت های  گزارش   ',
                'verbose_name_plural': 'مدیریت فعالیت های گزارش    ',
            },
        ),
    ]
