# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion
import meeting_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('boolean', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'دیتابیس  bool',
                'verbose_name_plural': 'دیتابیس  bool',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('complate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': ' جلسه',
                'verbose_name_plural': ' جلسه',
            },
        ),
        migrations.CreateModel(
            name='TextDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'دیتابیس متن ها',
                'verbose_name_plural': 'دیتابیس متن ها',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('JobBankRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JobBankRelated', to='organization_app.jobbank')),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MemberRelated', to='meeting_app.meeting', verbose_name='پروفایل جلسه مرتبط ')),
            ],
            options={
                'verbose_name': 'حاظرین جلسات',
                'verbose_name_plural': 'حاظرین جلسات',
            },
        ),
        migrations.CreateModel(
            name='MeetingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingType', models.CharField(choices=[('meet', 'جلسه'), ('committee', 'کمیته'), ('review', 'بازنگری')], default='meet', max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('firstSuccessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstSuccessor', to='organization_app.jobbank', verbose_name='دبیر ')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='organization_app.jobbank', verbose_name='دبیر ')),
                ('membersPrimary', models.ManyToManyField(to='organization_app.jobbank')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibleMetting', to='organization_app.jobbank', verbose_name='دبیر ')),
                ('secondSuccessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondSuccessor', to='organization_app.jobbank', verbose_name='دبیر ')),
            ],
            options={
                'verbose_name': 'پروفایل جلسات',
                'verbose_name_plural': 'پروفایل جلسات',
            },
        ),
        migrations.CreateModel(
            name='MeetingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planDocument', models.FileField(blank=True, null=True, upload_to=meeting_app.models.user_directory_path_meetingDocument)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedPlan', to='meeting_app.meeting', verbose_name='پروفایل جلسه مرتبط ')),
            ],
            options={
                'verbose_name': 'طرح  جلسه',
                'verbose_name_plural': 'طرح  جلسه',
            },
        ),
        migrations.CreateModel(
            name='MeetingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membersOther', models.TextField(blank=True, null=True)),
                ('compated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedMember', to='meeting_app.meeting', verbose_name='تاریخ جلسه مرتبط ')),
                ('membersSecondary', models.ManyToManyField(related_name='membersSecondary', to='meeting_app.member')),
            ],
            options={
                'verbose_name': 'اعضای جلسه',
                'verbose_name_plural': 'اعضای جلسه',
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedInvitation', to='meeting_app.meeting', verbose_name='پروفایل جلسه مرتبط ')),
            ],
            options={
                'verbose_name': 'دعوت نامه جلسه',
                'verbose_name_plural': 'دعوت نامه جلسه',
            },
        ),
        migrations.CreateModel(
            name='MeetingEnactment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedEnactment', to='meeting_app.meeting', verbose_name='پروفایل جلسه مرتبط ')),
                ('responsibleExecutive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibleMeetingEnactmentExecutive', to='organization_app.jobbank', verbose_name='مسئول اجرا مصوبه ')),
                ('responsibleFollow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibleMeetingEnactmentFollow', to='organization_app.jobbank', verbose_name='مسئول پیگیری اجرا مصوبه ')),
            ],
            options={
                'verbose_name': 'صورت  جلسه',
                'verbose_name_plural': 'صورت  جلسه',
            },
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persentDocument', models.FileField(blank=True, null=True, upload_to=meeting_app.models.user_directory_path_meetingDocument)),
                ('minuteDocument', models.FileField(blank=True, null=True, upload_to=meeting_app.models.user_directory_path_meetingDocument)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedDocument', to='meeting_app.meeting', verbose_name='پروفایل جلسه مرتبط ')),
            ],
            options={
                'verbose_name': 'فایل  جلسه',
                'verbose_name_plural': 'فایل  جلسه',
            },
        ),
        migrations.CreateModel(
            name='MeetingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingDate', models.DateField()),
                ('meetingTime', models.TimeField()),
                ('meetingTimeDuration', models.TimeField()),
                ('meetingPlace', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedDate', to='meeting_app.meeting', verbose_name='پروفایل جلسه مرتبط ')),
            ],
            options={
                'verbose_name': 'تاریخ جلسات',
                'verbose_name_plural': 'تاریخ جلسات',
            },
        ),
        migrations.CreateModel(
            name='MeetingAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('timeDuration', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meetingRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedAgenda', to='meeting_app.meeting', verbose_name='پروفایل جلسه مرتبط ')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibleMettingAgenda', to='organization_app.jobbank', verbose_name='دبیر ')),
            ],
            options={
                'verbose_name': 'دستور  جلسه',
                'verbose_name_plural': 'دستور  جلسه',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='meetingProfileRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingProfileRelated', to='meeting_app.meetingprofile', verbose_name='پروفایل جلسه مرتبط  '),
        ),
        migrations.CreateModel(
            name='ConfirmationDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('confirm', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('pending', 'در دست بررسی')], default='pending', max_length=75)),
                ('text', models.TextField(blank=True, null=True)),
                ('MeetingRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MeetingRelatedConfirmation', to='meeting_app.meeting')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmationMeetingProfile', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'دیتابیس  کانفرم شدن',
                'verbose_name_plural': 'دیتابیس  کانفرم شدن',
            },
        ),
    ]
