# Generated by Django 4.1.7 on 2023-07-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetinginvitation',
            options={'verbose_name': 'دعوت به جلسه جلسه', 'verbose_name_plural': 'دعوت به جلسه جلسه'},
        ),
    ]
