# Generated by Django 4.1.7 on 2023-08-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0004_alter_member_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingmember',
            old_name='compated',
            new_name='complated',
        ),
    ]
