# Generated by Django 4.1.7 on 2023-08-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0005_rename_compated_meetingmember_complated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingplan',
            options={'verbose_name': 'فایل ارائه  جلسه', 'verbose_name_plural': 'فایل ارائه  جلسه'},
        ),
    ]
