# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import library_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fileUploaded', models.FileField(blank=True, null=True, upload_to=library_app.models.user_directory_path_library)),
                ('imageUploaded', models.FileField(blank=True, null=True, upload_to=library_app.models.user_directory_path_library)),
                ('category', models.CharField(choices=[('all', 'همه'), ('video', 'فیلم'), ('article', 'مقاله')], default='video', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'فایل  کتابخانه',
                'verbose_name_plural': 'فایل  کتابخانه',
            },
        ),
    ]
