# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('warning', 'warning'), ('primary', 'primary'), ('success', 'success')], max_length=100)),
                ('personalStatus', models.CharField(choices=[('read', 'خوانده شده'), ('pending', 'مشاهده نشده')], default='pending', max_length=100)),
                ('icon', models.CharField(blank=True, choices=[('warning-sign2', 'warning-sign'), ('check-all2', 'check-all'), ('alarm2', 'alarm')], default='alarm', max_length=100, null=True)),
                ('link', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderProfile', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'اطلاعیه ',
                'verbose_name_plural': 'اطلاعیه ',
            },
        ),
    ]
