# Generated by Django 4.1.7 on 2023-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
