# Generated by Django 4.1.7 on 2023-06-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('how', models.CharField(max_length=250)),
                ('actor', models.CharField(max_length=250)),
                ('reciver', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'جدول ارتباطات خارحی ',
                'verbose_name_plural': 'جدول ارتباطات خارحی ',
            },
        ),
    ]
