# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standardTable_app', '0001_initial'),
        ('profile_app', '0001_initial'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('within', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dabir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dabirManagementReview', to='profile_app.profile')),
                ('members', models.ManyToManyField(related_name='membersManagementReview', to='profile_app.profile')),
                ('systemProfileManagementReview', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='systemProfileManagementReview', to='standardTable_app.standard')),
            ],
            options={
                'verbose_name': ' پروفایل بازنگری و مدیریت',
                'verbose_name_plural': ' پروفایل بازنگری و مدیریت',
            },
        ),
        migrations.CreateModel(
            name='InviteManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateManagementReview', models.DateTimeField(blank=True, null=True)),
                ('locationManagementReview', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ProfileManagementReviewRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileManagementReviewRelated', to='managementReview_app.profilemanagementreview')),
                ('guests', models.ManyToManyField(related_name='guestsManagementReview', to='profile_app.profile')),
            ],
            options={
                'verbose_name': ' دعوت نامه جلسه بازنگری مدیریت',
                'verbose_name_plural': 'دعوت نامه جلسه بازنگری مدیریت ',
            },
        ),
        migrations.CreateModel(
            name='InputManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systemInputManagementReview', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='systemInputManagementReview', to='standardTable_app.standard')),
            ],
            options={
                'verbose_name': 'ورودی های بازنگری و مدیریت',
                'verbose_name_plural': 'ورودی های بازنگری و مدیریت',
            },
        ),
        migrations.CreateModel(
            name='approveManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=250, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ProfileManagementReviewApprovedRelated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileManagementReviewApprovedRelated', to='managementReview_app.profilemanagementreview')),
                ('executVahed', models.ManyToManyField(related_name='executVahedApprove', to='organization_app.vahed')),
                ('trackVahed', models.ManyToManyField(related_name='trackVahed', to='organization_app.vahed')),
            ],
            options={
                'verbose_name': 'مصوبات جلسات',
                'verbose_name_plural': 'مصوبات جلسات',
            },
        ),
    ]
