# Generated by Django 4.1.7 on 2023-07-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0002_alter_jobbank_profile'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileManagementChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('typeChange', models.CharField(blank=True, max_length=250, null=True)),
                ('subjectChange', models.CharField(blank=True, max_length=250, null=True)),
                ('locationChange', models.TextField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('resonChange', models.TextField(blank=True, null=True)),
                ('goalChange', models.TextField(blank=True, null=True)),
                ('effectChange', models.TextField(blank=True, null=True)),
                ('firstCheckChange', models.TextField(blank=True, null=True)),
                ('preparationChange', models.TextField(blank=True, null=True)),
                ('effectiveChange', models.TextField(blank=True, null=True)),
                ('criterionChange', models.TextField(blank=True, null=True)),
                ('resultChnage', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('VahedChange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VahedChange', to='organization_app.vahed')),
                ('changeProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changeProfile', to='profile_app.profile')),
                ('criterionChangeProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterionChangeProfile', to='profile_app.profile')),
                ('effectChangeProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectChangeProfile', to='profile_app.profile')),
                ('effectiveChangeProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveChangeProfile', to='profile_app.profile')),
                ('firstCheckChangeProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstCheckChangeProfile', to='profile_app.profile')),
                ('preparationChangeProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparationChangeProfile', to='profile_app.profile')),
                ('resultChnageProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultChnageProfile', to='profile_app.profile')),
            ],
            options={
                'verbose_name': ' پروفایل بازنگری و مدیریت',
                'verbose_name_plural': ' پروفایل بازنگری و مدیریت',
            },
        ),
    ]
