# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process_app', '0001_initial'),
        ('profile_app', '0001_initial'),
        ('organization_app', '0001_initial'),
        ('committee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته بندی سوال ',
                'verbose_name_plural': 'دسته بندی سوال ',
            },
        ),
        migrations.CreateModel(
            name='RiskActivityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'به اتمام رسیده'), ('doing', 'درحال انجام'), ('doNot', 'انجام نشد')], default='doing', max_length=75)),
                ('activity', models.CharField(choices=[('team', 'تعریف تیم ها '), ('identification', 'شناسایی ریسک'), ('Conclusion', 'جمع بندی ریسک'), ('measurement', 'ارزیابی'), ('evaluation', 'ارزیابی ریسک')], max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hoze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityHoze', to='process_app.hoze')),
                ('nextActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NeActivity', to='risk_app.riskactivitymanager')),
                ('previousActivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrActivity', to='risk_app.riskactivitymanager')),
                ('reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReciverProfile', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'مدیریت فعالیت های ریسک   ',
                'verbose_name_plural': 'مدیریت فعالیت های ریسک   ',
            },
        ),
        migrations.CreateModel(
            name='RiskIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskFailureModes', models.CharField(max_length=250, verbose_name='عنوان ریسک')),
                ('riskCauses', models.TextField(max_length=250, verbose_name='علل بروز خطا')),
                ('riskEffects', models.TextField(max_length=250, verbose_name='اثرات بروز خطا')),
                ('currentAction', models.TextField(verbose_name='کنترل های فعلی')),
                ('status', models.CharField(choices=[('identification', 'identification'), ('measurement', 'measurement'), ('Conclusion', 'Conclusion'), ('evaluation', 'evaluation')], default='identification', max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RiskActivityIdentification', to='risk_app.riskactivitymanager', verbose_name='قعالیت مرتبط')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessGroupRiskIdentification', to='process_app.group', verbose_name='گروه فرآیندی ')),
                ('hoze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskHoze', to='process_app.hoze')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessRiskIdentification', to='process_app.process', verbose_name='فرآیند')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecommenderRiskIdentification', to='profile_app.profile', verbose_name='پیشنهاد دهنده')),
            ],
            options={
                'verbose_name': 'شناسایی ریسک   ',
                'verbose_name_plural': ' شناسایی ریسک  ',
            },
        ),
        migrations.CreateModel(
            name='RiskMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskSeverity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='شدت اثر')),
                ('riskOccurrence', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='احتمال وقوع')),
                ('riskDetection', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قابلیت کشف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RiskActivityMeasurement', to='risk_app.riskactivitymanager', verbose_name='قعالیت مرتبط')),
                ('riskIdentificated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RiskIdentificated', to='risk_app.riskidentification', verbose_name='ریسک شناسایی شده')),
            ],
            options={
                'verbose_name': 'ارزیابی ریسک',
                'verbose_name_plural': 'ارزیابی ریسک',
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'تعریف تیم ها '), ('2', 'شناسایی ریسک'), ('2', 'بررسی ریسک های شناسایی شده'), ('3', 'ارزیابی ریسک'), ('4', 'پایان'), ('5', 'پایان')], default='1', max_length=75)),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committeeRisk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committeeRisk', to='committee_app.committee')),
            ],
            options={
                'verbose_name': 'پروفایل ریسک ',
                'verbose_name_plural': 'پروفایل ریسک ',
            },
        ),
        migrations.CreateModel(
            name='RiskTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vahed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vahedMortabetRisk', to='organization_app.vahed')),
            ],
            options={
                'verbose_name': 'سرفصل ریسک',
                'verbose_name_plural': 'سرفصل ریسک',
            },
        ),
        migrations.CreateModel(
            name='RiskTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hoze', models.ManyToManyField(related_name='RiskTeamHoze', to='process_app.hoze')),
                ('memberProfile', models.ManyToManyField(to='profile_app.profile')),
                ('riskProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskProfileTeamRelated', to='risk_app.riskprofile')),
                ('riskTopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RiskTeamTopic', to='risk_app.risktopic')),
            ],
            options={
                'verbose_name': 'تیم ارزشیابی ریسک ',
                'verbose_name_plural': 'تیم ارزشیابی ریسک  ',
            },
        ),
        migrations.CreateModel(
            name='RiskProcessRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('riskProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskProfile', to='risk_app.riskprofile')),
            ],
            options={
                'verbose_name': 'فرآیند مرتبط با ریسک',
                'verbose_name_plural': 'فرآیند مرتبط با ریسک',
            },
        ),
        migrations.CreateModel(
            name='RiskProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgRiskSeverity', models.FloatField(blank=True, null=True, verbose_name='میانگین شدت اثر')),
                ('avgRiskOccurrence', models.FloatField(blank=True, null=True, verbose_name='میانگین احتمال وقوع')),
                ('avgRiskDetection', models.FloatField(blank=True, null=True, verbose_name='میانگین قابلیت کشف')),
                ('rpn', models.FloatField(blank=True, null=True, verbose_name='اولویت ریسک')),
                ('rpnAdjusted', models.FloatField(blank=True, null=True, verbose_name='اولویت ریسک تعدیل شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_app.process', verbose_name='فرآیند')),
                ('riskMeasurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_app.riskmeasurement', verbose_name='ریسک اریابی شده')),
                ('riskProfileRelated', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='riskProfileRelatedProcess', to='risk_app.riskprofile')),
            ],
            options={
                'verbose_name': 'ریسک فرآیند',
                'verbose_name_plural': 'ریسک فرآیند',
            },
        ),
        migrations.AddField(
            model_name='riskidentification',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamRiskIdentification', to='risk_app.riskteam', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='riskactivitymanager',
            name='riskProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskProfileActivity', to='risk_app.riskprofile'),
        ),
        migrations.AddField(
            model_name='riskactivitymanager',
            name='riskTopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityRiskTopic', to='risk_app.risktopic'),
        ),
        migrations.AddField(
            model_name='riskactivitymanager',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SenderProfile', to='profile_app.profile'),
        ),
        migrations.AddField(
            model_name='riskactivitymanager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RiskTeamActivityManager', to='risk_app.riskteam'),
        ),
        migrations.CreateModel(
            name='extraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.TextField(blank=True, null=True)),
                ('eghdam', models.TextField(blank=True, null=True)),
                ('masol', models.TextField(blank=True, null=True)),
                ('tarikh', models.TextField(blank=True, null=True)),
                ('natije', models.TextField(blank=True, null=True)),
                ('newRisk', models.TextField(blank=True, null=True)),
                ('tarif', models.TextField(blank=True, null=True)),
                ('dec', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('RiskProcessRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskProcessRelatedExtra', to='risk_app.riskprocess', verbose_name='اطلاعات اضاقی')),
            ],
            options={
                'verbose_name': ' اطلاعات اضافی ریسک',
                'verbose_name_plural': ' اطلاعات اضافی ریسک',
            },
        ),
        migrations.CreateModel(
            name='RiskIdentificationSelecting',
            fields=[
                ('riskidentification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='risk_app.riskidentification')),
                ('riskIdentifications', models.ManyToManyField(related_name='riskIdentifications', to='risk_app.riskidentification')),
            ],
            options={
                'verbose_name': 'انتخاب ریسک های شناسایی شده   ',
                'verbose_name_plural': 'انتخاب ریسک های شناسایی شده',
            },
            bases=('risk_app.riskidentification',),
        ),
    ]
