# Generated by Django 4.1.7 on 2023-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='step',
            field=models.CharField(choices=[('1', 'تعریف تیم ها '), ('2', 'شناسایی ریسک'), ('2', 'بررسی ریسک های شناسایی شده'), ('3', 'ارزیابی ریسک'), ('4', 'پایان')], default='1', max_length=75),
        ),
    ]
