# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabaghe', models.CharField(max_length=250)),
                ('beneficiary', models.CharField(max_length=250)),
                ('manzar', models.CharField(max_length=250)),
                ('beneficiaryType', models.CharField(max_length=250)),
                ('beneficiaryHoze', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('vaziyatNow', models.CharField(max_length=250)),
                ('vaiyatMatlob', models.CharField(max_length=250)),
                ('expectations', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لیست ذینفعان سازمان',
                'verbose_name_plural': 'لیست ذینفعان سازمان',
            },
        ),
    ]
