# Generated by Django 4.1.7 on 2023-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ذینفعان',
                'verbose_name_plural': 'ذینفعان',
            },
        ),
        migrations.CreateModel(
            name='ClassificationBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طبقه بندی ذینفعان',
                'verbose_name_plural': 'طبقه بندی ذینفعان',
            },
        ),
        migrations.CreateModel(
            name='CurrentNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نیاز های فعلی',
                'verbose_name_plural': 'نیاز های فعلی',
            },
        ),
        migrations.CreateModel(
            name='FutureExpectations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'انتظارات آتی',
                'verbose_name_plural': 'انتظارات آتی',
            },
        ),
        migrations.CreateModel(
            name='GroupBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گروه ذینفعان',
                'verbose_name_plural': 'گروه ذینفعان',
            },
        ),
    ]
