# Generated by Django 4.1.7 on 2023-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True, verbose_name='سوال')),
                ('answer', models.TextField(blank=True, null=True)),
                ('typeQuestion', models.CharField(blank=True, choices=[('learn', 'آموزشی')], max_length=250, null=True, verbose_name='روند شاخص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' سوالات متداول  ',
                'verbose_name_plural': 'سوالات متداول  ',
            },
        ),
    ]
